title: A Travel Blog
logo:
url: https://dedunu.click
baseurl:

cdn: https://cdn.dedunu.info

sass:
  sass_dir: _sass

author_name: "Dedunu Dhananjaya"
author_url: "https://dedunu.info"
author_image: dedunu.jpeg

paginate: 5
paginate_path: '/blog/page:num/'
plugins: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
